import Footer from "@components/Footer";
import Header from "@components/Header";

import Head from "next/head";

export default function Home({ children }) {
  return (
    <>
      <Head>
        <title>UX Geek | Varun</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>
        {`
          main {
            height: 96vh;
          }
        `}
      </style>

      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
